name: Update README

on:
  create:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Update README
        run: |
          cd ${{ github.workspace }}
          mv README.md tmp.md
          perl -n -e 'print $_ if !$found; $found=1 if m/# LABS/;' tmp.md > README.md
          rm tmp.md
          echo "" >> README.md
          git branch --format='%(refname:short)'
          git branch --format='%(refname:short)' | sed 's/* //g' | xargs -I {} echo "* [{}](https://github.com/icann/OCTO-TE-labs/tree/{})" >> README.md
          CHECKOUT="NO"
          git diff --quiet README.md || CHECKOUT="YES"
          if [ "$CHECKOUT" == "YES" ]; then
            git add README.md
            git commit -m "Update README with branch list"
            git push origin main
          else
            echo "NO CHANGES"
          fi
          echo "DONE"          
